name: Deploy

on:
  workflow_dispatch:
    inputs:
      projeto:
        description: "api ou cronjob"
        required: true
        type: choice
        options:
          - api
          - cronjob

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Desativar cron para API
        if: github.event.inputs.projeto == 'api'
        run: |
          sed -i 's|^\(\*/5 \* \* \* \* php artisan schedule:run\)|# \1|' crontab/crontab_prod

      - name: Ativar cron para CronJob
        if: github.event.inputs.projeto == 'cronjob'
        run: |
          sed -i 's|^# \(.*php artisan schedule:run.*\)|\1|' crontab/crontab_prod

      - name: Mostrar resultado
        run: |
          echo "Projeto: ${{ github.event.inputs.projeto }}"
          cat crontab/crontab_prod
